CREATE DATABASE IF NOT EXISTS goomer;

USE goomer;

CREATE TABLE restaurants (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  photo VARCHAR(1000) NOT NULL,
  name VARCHAR(50) NOT NULL,
  addres VARCHAR(50) NOT NULL
); 

CREATE TABLE products(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  photo VARCHAR(1000) NOT NULL,
  name VARCHAR(50) NOT NULL,
  price INTEGER NOT NULL,
  category VARCHAR(50) NOT NULL,
  id_restaurant INTEGER NOT NULL,
  FOREIGN KEY fk_restaurant (id_restaurant) REFERENCES goomer.restaurants (id) ON DELETE CASCADE
);
